### ISSUE TITLE
Code-Kommentare

### ISSUE THREAD

**Issue by aspecialkey** [oliverhuckfeldt/pattframe#24]
momentan gibts fast keine Kommentare
--muss noch gemacht werden

**Comment by majacal** [comment]
ja mit javadoc tags ... so das wir nen javadoc html gerendert haben... 

bekannte tags:
https://de.wikipedia.org/wiki/Javadoc

<table class="wikitable">
<tbody><tr>
<th>Tag und Parameter</th>
<th>Ausgabe</th>
<th>Verwendung in</th>
<th>seit</th>
</tr>
<tr>
<td><code>@author</code> name</td>
<td>Beschreibt den Autor.</td>
<td>Klasse, Interface</td>
<td></td>
</tr>
<tr>
<td><code>@version</code> version</td>
<td>Erzeugt einen Versionseintrag. Maximal einmal pro Klasse oder Interface.</td>
<td>Klasse, Interface</td>
<td></td>
</tr>
<tr>
<td><code>@since</code> jdk-version</td>
<td>Seit wann die Funktionalität existiert.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td></td>
</tr>
<tr>
<td><code>@see</code> reference</td>
<td>Erzeugt einen Link auf ein anderes Element der Dokumentation.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td></td>
</tr>
<tr>
<td><code>@serial</code></td>
<td>Bei einem <code>Serializable Object</code> beschreibt es die serialisierten Daten des Objekts.</td>
<td>Klasse</td>
<td></td>
</tr>
<tr>
<td><code>@serialField</code></td>
<td>Dokumentiert ein Feld von einem Serializable Objekt.</td>
<td>Klasse, Methode</td>
<td></td>
</tr>
<tr>
<td><code>@param</code> name description</td>
<td>Parameterbeschreibung einer Methode.</td>
<td>Methode</td>
<td></td>
</tr>
<tr>
<td><code>@return</code> description</td>
<td>Beschreibung des Rückgabewerts einer Methode.</td>
<td>Methode</td>
<td></td>
</tr>
<tr>
<td><code>@exception</code> classname description<br>
<code>@throws</code> classname description</td>
<td>Beschreibung einer Exception, die von dieser Methode geworfen werden kann.</td>
<td>Methode</td>
<td></td>
</tr>
<tr>
<td><code>@deprecated</code> description</td>
<td>Beschreibt eine veraltete Methode, die nicht mehr verwendet werden sollte. Sollte ab Java 5.0 immer mit der <code>@Deprecated</code>-Annotation verwendet werden.</td>
<td>Methode</td>
<td></td>
</tr>
<tr>
<td><code>{@inheritDoc}</code></td>
<td>Kopiert die Beschreibung aus der überschriebenen Methode.</td>
<td>Überschreibende Methode</td>
<td>1.4.0</td>
</tr>
<tr>
<td><code>{@link <i>reference</i>}</code></td>
<td>Link zu einem anderen Symbol.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td></td>
</tr>
<tr>
<td><code>{@linkPlain <i>reference</i>}</code></td>
<td>Der Link wird in Standardtext statt in Quelltextzeichensatz angezeigt.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td>1.4.0</td>
</tr>
<tr>
<td><code>{@value}</code></td>
<td>Gibt den Wert eines konstanten Feldes zurück.</td>
<td>Statisches Feld</td>
<td>1.4.0</td>
</tr>
<tr>
<td><code>{@docRoot}</code></td>
<td>Gibt den absoluten Pfad zum Hauptverzeichnis wieder.</td>
<td>Package, Klassen, Felder, Methoden</td>
<td></td>
</tr>
<tr>
<td><code>{@code}</code></td>
<td>Formatiert Text buchstabengetreu mit dem Quelltextzeichensatz (entsprechend <tt>&lt;code&gt;</tt>) und unterdrückt die Interpretierung von beinhalteten HTML oder Javadoc-Tags.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td>5.0</td>
</tr>
<tr>
<td><code>{@literal}</code></td>
<td>Kennzeichnet buchstabengetreuen Text und unterdrückt die Interpretierung von beinhalteten HTML oder Javadoc-Tags.</td>
<td>Klasse, Interface, Instanzvariable, Methode</td>
<td>5.0</td>
</tr>
</tbody></table>

**Comment by markweigelt** [comment]
Beschluss 13.12.2016: Wir kommentieren auf Deutsch.

**Comment by markweigelt** [comment]
Ich habe die formalen JavaDoc-Kommentare eingefügt - die Kommentare sind aber noch nicht befüllt und ausgefüllt. Die Kommentare müssen noch mit Leben (und Beschreibungen) gefüllt werden. Ich hoffe dennoch es erleicht die weitere Arbeit.

**Comment by markweigelt** [comment]
In IntelliJ kann über "Tools" > "Generate Java Doc" ein JavaDoc erzeugt werden.
Dabei habe ich den Slider auf "private" gestellt.
Bei "Other command line arguments" habe ich folgendes eingetragen, damit auch Umlaute funktionieren: `-encoding utf8 -docencoding utf8 -charset utf8 `
